var D4Option = (function(){
	var method = {};
	var obj = {};
	var options = [
		// ver = ori|dlc
		// job = com|dru|bab|soc|rog|nec
		// parts = com|wep|sub|hel|che|glo|pan|boo|amu|rin
		// type = com|off|def|uti|res|mob
		// name = options name
		
		//투구
		{ver:'ori', job:'com', type:'com', parts:'hel',						name:'기본 기술 공격속도 증가'},
		{ver:'ori', job:'com', type:'com', parts:'hel',						name:'군중제어 효과 지속시간'},
		{ver:'ori', job:'com', type:'com', parts:'hel',						name:'받는 치유량'},
		{ver:'ori', job:'com', type:'com', parts:'hel',						name:'재사용 대기시간 감소'},
		{ver:'ori', job:'com', type:'com', parts:'hel',						name:'처치 시 생명력'},
		{ver:'ori', job:'com', type:'com', parts:'hel',					name:'총 방어도'},
		{ver:'ori', job:'com', type:'com', parts:'hel',					name:'최대 생명력'},
		{ver:'ori', job:'com', type:'com', parts:'hel',						name:'최근 피해를 받지 않았을 때 생명력 재생량'},
		{ver:'ori', job:'com', type:'com', parts:'hel',						name:'모든 능력치'},
		{ver:'ori', job:'com', type:'com', parts:'hel',						name:'힘'},
		{ver:'ori', job:'com', type:'com', parts:'hel',						name:'민첩'},
		{ver:'ori', job:'com', type:'com', parts:'hel',						name:'의지력'},
		{ver:'ori', job:'com', type:'com', parts:'hel',						name:'지능'},
		{ver:'ori', job:'com', type:'com', parts:'hel',						name:'화염 저항'},
		{ver:'ori', job:'com', type:'com', parts:'hel',						name:'냉기 저항'},
		{ver:'ori', job:'com', type:'com', parts:'hel',						name:'독 저항'},
		{ver:'ori', job:'com', type:'com', parts:'hel',						name:'번개 저항'},
		{ver:'ori', job:'com', type:'com', parts:'hel',						name:'암흑 저항'},
		{ver:'ori', job:'dru', type:'job', parts:'hel',						name:'최대 영력'},
		{ver:'ori', job:'dru', type:'job', parts:'hel',					name:'보호막 생성량'},
		{ver:'ori', job:'dru', type:'skl', parts:'hel',						name:'늑대 무리'},
		{ver:'ori', job:'dru', type:'skl', parts:'hel',						name:'맹독 덩굴'},
		{ver:'ori', job:'dru', type:'skl', parts:'hel',						name:'큰 까마귀'},
		{ver:'ori', job:'bab', type:'job', parts:'hel',						name:'최대 분노'},
		{ver:'ori', job:'bab', type:'job', parts:'hel',					name:'보호막 생성량'},
		{ver:'ori', job:'bab', type:'skl', parts:'hel',						name:'강철 손아귀'},
		{ver:'ori', job:'bab', type:'skl', parts:'hel',						name:'결정타'},
		{ver:'ori', job:'bab', type:'skl', parts:'hel',						name:'파열'},
		{ver:'ori', job:'soc', type:'job', parts:'hel',						name:'최대 마나'},
		{ver:'ori', job:'soc', type:'job', parts:'hel',					name:'보호막 생성량'},
		{ver:'ori', job:'soc', type:'job', parts:'hel',						name:'보호막이 있을 때 행운 적중 확률'},
		{ver:'ori', job:'soc', type:'skl', parts:'hel',						name:'번개 창'},
		{ver:'ori', job:'soc', type:'skl', parts:'hel',						name:'얼음 칼날'},
		{ver:'ori', job:'soc', type:'skl', parts:'hel',						name:'히드라'},
		{ver:'ori', job:'rog', type:'job', parts:'hel',						name:'최대 기력'},
		{ver:'ori', job:'rog', type:'skl', parts:'hel',						name:'냉기 주입'},
		{ver:'ori', job:'rog', type:'skl', parts:'hel',						name:'독 주입'},
		{ver:'ori', job:'rog', type:'skl', parts:'hel',						name:'암흑 주입'},
		{ver:'ori', job:'nec', type:'job', parts:'hel',						name:'최대 정수'},
		{ver:'ori', job:'nec', type:'job', parts:'hel',						name:'해골 마법학자 가시 %'},
		{ver:'ori', job:'nec', type:'skl', parts:'hel',						name:'가시박힌 철관'},
		{ver:'ori', job:'nec', type:'skl', parts:'hel',						name:'노화'},

		//가슴
		{ver:'ori', job:'com', type:'com', parts:'che',					name:'총 방어도'},
		{ver:'ori', job:'com', type:'com', parts:'che',					name:'최대 생명력'},
		{ver:'ori', job:'com', type:'com', parts:'che',						name:'가시'},
		{ver:'ori', job:'com', type:'com', parts:'che',						name:'공격력'},
		{ver:'ori', job:'com', type:'com', parts:'che',						name:'궁극기 기술 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'che',						name:'제어 방해 지속시간 감소'},
		{ver:'ori', job:'com', type:'com', parts:'che',						name:'피해 감소'},
		{ver:'ori', job:'com', type:'com', parts:'che',						name:'근거리 피해 감소'},
		{ver:'ori', job:'com', type:'com', parts:'che',						name:'원거리 피해 감소'},
		{ver:'ori', job:'dru', type:'com', parts:'che',					name:'보호막 생성량'},
		{ver:'ori', job:'com', type:'com', parts:'che',						name:'모든 능력치'},
		{ver:'ori', job:'com', type:'com', parts:'che',						name:'힘'},
		{ver:'ori', job:'com', type:'com', parts:'che',						name:'민첩'},
		{ver:'ori', job:'com', type:'com', parts:'che',						name:'의지력'},
		{ver:'ori', job:'com', type:'com', parts:'che',						name:'지능'},
		{ver:'ori', job:'com', type:'com', parts:'che',						name:'화염 저항'},
		{ver:'ori', job:'com', type:'com', parts:'che',						name:'냉기 저항'},
		{ver:'ori', job:'com', type:'com', parts:'che',						name:'독 저항'},
		{ver:'ori', job:'com', type:'com', parts:'che',						name:'번개 저항'},
		{ver:'ori', job:'com', type:'com', parts:'che',						name:'암흑 저항'},
		{ver:'ori', job:'dru', type:'job', parts:'che',						name:'변신 상태에서 공격력'},
		{ver:'ori', job:'dru', type:'job', parts:'che',						name:'인간 형상일 때 공격력'},
		{ver:'ori', job:'dru', type:'job', parts:'che',						name:'독 피해 증가'},
		{ver:'ori', job:'dru', type:'job', parts:'che',						name:'물리 피해 증가'},
		{ver:'ori', job:'dru', type:'job', parts:'che',						name:'번개 피해 증가'},
		{ver:'ori', job:'dru', type:'off', parts:'che',						name:'곰인간 일때 피해 증가'},
		{ver:'ori', job:'dru', type:'off', parts:'che',						name:'늑대인간 일때 피해 증가'},
		{ver:'ori', job:'dru', type:'off', parts:'che',						name:'대지기술 피해 증가'},
		{ver:'ori', job:'dru', type:'off', parts:'che',						name:'동료 피해 증가'},
		{ver:'ori', job:'dru', type:'off', parts:'che',						name:'폭풍기술 피해 증가'},
		{ver:'ori', job:'dru', type:'def', parts:'che',						name:'보강 상태에서 피해 감소'},
		{ver:'ori', job:'dru', type:'def', parts:'che',						name:'중독 적에게 피해 감소'},
		{ver:'ori', job:'dru', type:'skl', parts:'che',						name:'대지 방벽'},
		{ver:'ori', job:'dru', type:'skl', parts:'che',						name:'쇠약의 포효'},
		{ver:'ori', job:'dru', type:'skl', parts:'che',						name:'피의 울부짖음'},
		{ver:'ori', job:'dru', type:'skl', parts:'che',						name:'회오리 갑옷'},
		{ver:'ori', job:'bab', type:'job', parts:'che',					name:'보호막 생성량'},
		{ver:'ori', job:'bab', type:'job', parts:'che',						name:'보강 재생량'},
		{ver:'ori', job:'bab', type:'job', parts:'che',						name:'쌍수 무기 공격력'},
		{ver:'ori', job:'bab', type:'job', parts:'che',						name:'양손 둔기 공격력'},
		{ver:'ori', job:'bab', type:'job', parts:'che',						name:'양손 베는 무기 공격력'},
		{ver:'ori', job:'bab', type:'off', parts:'che',						name:'물리 피해 증가'},
		{ver:'ori', job:'bab', type:'off', parts:'che',						name:'난투 피해 증가'},
		{ver:'ori', job:'bab', type:'off', parts:'che',						name:'무기숙련 피해 증가'},
		{ver:'ori', job:'bab', type:'off', parts:'che',						name:'새로운 무기로 교체하는 기술 피해 증가'},
		{ver:'ori', job:'bab', type:'def', parts:'che',						name:'보강 상태에서 피해 감소'},
		{ver:'ori', job:'bab', type:'def', parts:'che',						name:'출혈 적에게 받는 피해 감소'},
		{ver:'ori', job:'bab', type:'skl', parts:'che',						name:'도전의 외침'},
		{ver:'ori', job:'bab', type:'skl', parts:'che',						name:'발구르기'},
		{ver:'ori', job:'bab', type:'skl', parts:'che',						name:'집결의 함성'},
		{ver:'ori', job:'bab', type:'skl', parts:'che',						name:'철갑 피부'},
		{ver:'ori', job:'soc', type:'job', parts:'che',					name:'보호막 생성량'},
		{ver:'ori', job:'soc', type:'job', parts:'che',						name:'냉기 피해 증가'},
		{ver:'ori', job:'soc', type:'job', parts:'che',						name:'번개 피해 증가'},
		{ver:'ori', job:'soc', type:'job', parts:'che',						name:'화염 피해 증가'},
		{ver:'ori', job:'soc', type:'off', parts:'che',						name:'감전 기술 피해 증가'},
		{ver:'ori', job:'soc', type:'off', parts:'che',						name:'구현 기술 피해 증가'},
		{ver:'ori', job:'soc', type:'off', parts:'che',						name:'방화 기술 피해 증가'},
		{ver:'ori', job:'soc', type:'off', parts:'che',						name:'서리 기술 피해 증가'},
		{ver:'ori', job:'soc', type:'def', parts:'che',						name:'불타오름 적에게 받는 피해 감소'},
		{ver:'ori', job:'rog', type:'job', parts:'che',						name:'쌍수 무기의 공격력'},
		{ver:'ori', job:'rog', type:'job', parts:'che',						name:'원거리 무기의 공격력'},
		{ver:'ori', job:'rog', type:'job', parts:'che',						name:'독 피해 증가'},
		{ver:'ori', job:'rog', type:'job', parts:'che',						name:'물리 피해 증가'},
		{ver:'ori', job:'rog', type:'job', parts:'che',						name:'암흑 피해 증가'},
		{ver:'ori', job:'rog', type:'off', parts:'che',						name:'덫 기술 피해 증가'},
		{ver:'ori', job:'rog', type:'off', parts:'che',						name:'명사수 기술 피해 증가'},
		{ver:'ori', job:'rog', type:'off', parts:'che',						name:'새로운 무기로 교체하는 기술의 피해 증가'},
		{ver:'ori', job:'rog', type:'off', parts:'che',						name:'암살 기술 피해 증가'},
		{ver:'ori', job:'rog', type:'off', parts:'che',						name:'주입된 기술의 피해 증가(Imbuement : 회전 칼날, 연타, 꿰뚫는 사격, 질주, 그림자 걸음)'},
		{ver:'ori', job:'rog', type:'off', parts:'che',						name:'주입 기술 피해 증가(Imbued : 독 주입, 냉기 주입, 암흑 주입)'},
		{ver:'ori', job:'rog', type:'def', parts:'che',						name:'중독 적에게 받는 피해 감소'},
		{ver:'ori', job:'nec', type:'job', parts:'che',						name:'보강 생성량'},
		{ver:'ori', job:'nec', type:'job', parts:'che',						name:'최대 하수인 생명력'},
		{ver:'ori', job:'nec', type:'job', parts:'che',						name:'피의 구슬을 주운 후 4초 동안 공격력'},
		{ver:'ori', job:'nec', type:'job', parts:'che',						name:'물리 피해 증가'},
		{ver:'ori', job:'nec', type:'job', parts:'che',						name:'암흑 피해 증가'},
		{ver:'ori', job:'nec', type:'off', parts:'che',						name:'뼈 기술 피해 증가'},
		{ver:'ori', job:'nec', type:'off', parts:'che',						name:'소환 기술 피해 증가'},
		{ver:'ori', job:'nec', type:'off', parts:'che',						name:'어둠 기술 피해 증가'},
		{ver:'ori', job:'nec', type:'off', parts:'che',						name:'피 기술 피해 증가'},
		{ver:'ori', job:'nec', type:'def', parts:'che',						name:'보강 상태에서 피해 감소'},
		{ver:'ori', job:'nec', type:'def', parts:'che',						name:'지속 암흑피해 효과의 영향을 받는 적에게 받는 피해 감소'},

		//장갑
		{ver:'ori', job:'com', type:'com', parts:'glo',						name:'공격속도 증가'},
		{ver:'ori', job:'com', type:'com', parts:'glo',						name:'극대화 확률'},
		{ver:'ori', job:'com', type:'com', parts:'glo',						name:'부상당한 적에 대한 극대화 확률'},
		{ver:'ori', job:'com', type:'com', parts:'glo',						name:'부상당한 적에게 주는 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'glo',						name:'제압 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'glo',						name:'행운의 적중 확률'},
		{ver:'ori', job:'com', type:'com', parts:'glo',						name:'행운의 적중 : 감속 확률 최대'},
		{ver:'ori', job:'com', type:'com', parts:'glo',						name:'행운의 적중 : 최대 5% 확률로 생명력 치유'},
		{ver:'ori', job:'com', type:'com', parts:'glo',						name:'행운의 적중 : 최대 5% 확률로 주자원 회복'},
		{ver:'ori', job:'com', type:'com', parts:'glo',						name:'모든 능력치'},
		{ver:'ori', job:'com', type:'com', parts:'glo',						name:'힘'},
		{ver:'ori', job:'com', type:'com', parts:'glo',						name:'민첩'},
		{ver:'ori', job:'com', type:'com', parts:'glo',						name:'의지력'},
		{ver:'ori', job:'com', type:'com', parts:'glo',						name:'지능'},
		{ver:'ori', job:'dru', type:'job', parts:'glo',						name:'늑대인간 기술의 극대화 피해 증가'},
		{ver:'ori', job:'dru', type:'job', parts:'glo',						name:'대지 기술의 극대화 피해 증가'},
		{ver:'ori', job:'dru', type:'job', parts:'glo',						name:'번개 기술의 극대화 피해 증가'},
		{ver:'ori', job:'dru', type:'job', parts:'glo',						name:'폭풍 기술의 재사용 대기시간 감소'},
		{ver:'ori', job:'dru', type:'skl', parts:'glo',						name:'번개폭풍'},
		{ver:'ori', job:'dru', type:'skl', parts:'glo',						name:'산사태'},
		{ver:'ori', job:'dru', type:'skl', parts:'glo',						name:'쳐부수기'},
		{ver:'ori', job:'dru', type:'skl', parts:'glo',						name:'칼날발톱'},
		{ver:'ori', job:'dru', type:'skl', parts:'glo',						name:'회오리바람'},
		{ver:'ori', job:'bab', type:'job', parts:'glo',						name:'지속 물리 피해 증가'},
		{ver:'ori', job:'bab', type:'skl', parts:'glo',						name:'분쇄'},
		{ver:'ori', job:'bab', type:'skl', parts:'glo',						name:'손조의 망치'},
		{ver:'ori', job:'bab', type:'skl', parts:'glo',						name:'소용돌이'},
		{ver:'ori', job:'bab', type:'skl', parts:'glo',						name:'이중타격'},
		{ver:'ori', job:'bab', type:'skl', parts:'glo',						name:'지각변동'},
		{ver:'ori', job:'soc', type:'job', parts:'glo',						name:'번개 극대화 피해 증가'},
		{ver:'ori', job:'soc', type:'job', parts:'glo',						name:'지속 화염 피해 증가'},
		{ver:'ori', job:'soc', type:'skl', parts:'glo',						name:'번개줄기'},
		{ver:'ori', job:'soc', type:'skl', parts:'glo',						name:'소각'},
		{ver:'ori', job:'soc', type:'skl', parts:'glo',						name:'얼음보주'},
		{ver:'ori', job:'soc', type:'skl', parts:'glo',						name:'얼음파편'},
		{ver:'ori', job:'soc', type:'skl', parts:'glo',						name:'연쇄번개'},
		{ver:'ori', job:'soc', type:'skl', parts:'glo',						name:'화염구'},
		{ver:'ori', job:'nec', type:'job', parts:'glo',						name:'뼈 기술의 극대화 피해 증가'},
		{ver:'ori', job:'nec', type:'job', parts:'glo',						name:'지속 암흑 피해 증가'},
		{ver:'ori', job:'nec', type:'job', parts:'glo',						name:'해골 전사가 계승하는 가시'},
		{ver:'ori', job:'nec', type:'skl', parts:'glo',						name:'마름병'},
		{ver:'ori', job:'nec', type:'skl', parts:'glo',						name:'뼈 창'},
		{ver:'ori', job:'nec', type:'skl', parts:'glo',						name:'절단'},
		{ver:'ori', job:'nec', type:'skl', parts:'glo',						name:'피의 쇄도'},
		{ver:'ori', job:'nec', type:'skl', parts:'glo',						name:'피의 창'},

		//바지
		{ver:'ori', job:'com', type:'com', parts:'pan',						name:'가시'},
		{ver:'ori', job:'com', type:'com', parts:'pan',						name:'물약 용량'},
		{ver:'ori', job:'com', type:'com', parts:'pan',						name:'물약 획득 확률'},
		{ver:'ori', job:'com', type:'com', parts:'pan',						name:'받는 치유량'},
		{ver:'ori', job:'com', type:'com', parts:'pan',						name:'정예 처치 후 4초 공격력'},
		{ver:'ori', job:'com', type:'com', parts:'pan',						name:'총 방어도'},
		{ver:'ori', job:'com', type:'com', parts:'pan',						name:'최대 생명력'},
		{ver:'ori', job:'com', type:'com', parts:'pan',						name:'최근 피해를 받지 않았을 때 생명력 재생량'},
		{ver:'ori', job:'com', type:'com', parts:'pan',						name:'피해 감소'},
		{ver:'ori', job:'com', type:'com', parts:'pan',						name:'근거리 적에게 받는 피해 감소'},
		{ver:'ori', job:'com', type:'com', parts:'pan',						name:'원거리 적에게 받는 피해 감소'},
		{ver:'ori', job:'com', type:'com', parts:'pan',						name:'회피 확률'},
		{ver:'ori', job:'com', type:'com', parts:'pan',						name:'근거리 적에게 대한 회피 확률'},
		{ver:'ori', job:'com', type:'com', parts:'pan',						name:'모든 능력치'},
		{ver:'ori', job:'com', type:'com', parts:'pan',						name:'힘'},
		{ver:'ori', job:'com', type:'com', parts:'pan',						name:'민첩'},
		{ver:'ori', job:'com', type:'com', parts:'pan',						name:'의지력'},
		{ver:'ori', job:'com', type:'com', parts:'pan',						name:'지능'},
		{ver:'ori', job:'dru', type:'job', parts:'pan',						name:'곰인간 형상일때 총 방어도'},
		{ver:'ori', job:'dru', type:'def', parts:'pan',						name:'보강 상태에서 피해 감소'},
		{ver:'ori', job:'dru', type:'def', parts:'pan',						name:'중독 적에게 받는 피해 감소'},
		{ver:'ori', job:'dru', type:'skl', parts:'pan',						name:'광견병'},
		{ver:'ori', job:'dru', type:'skl', parts:'pan',						name:'바위'},
		{ver:'ori', job:'dru', type:'skl', parts:'pan',						name:'싹쓸바람'},
		{ver:'ori', job:'dru', type:'skl', parts:'pan',						name:'짓밟기'},
		{ver:'ori', job:'bab', type:'job', parts:'pan',						name:'광폭화 지속 시간'},
		{ver:'ori', job:'bab', type:'def', parts:'pan',						name:'보강 상태에서 피해 감소'},
		{ver:'ori', job:'bab', type:'def', parts:'pan',						name:'출혈 적에게 받는 피해 감소'},
		{ver:'ori', job:'bab', type:'skl', parts:'pan',						name:'도약'},
		{ver:'ori', job:'bab', type:'skl', parts:'pan',						name:'돌진'},
		{ver:'ori', job:'bab', type:'skl', parts:'pan',						name:'발차기'},
		{ver:'ori', job:'bab', type:'skl', parts:'pan',						name:'전장의 함성'},
		{ver:'ori', job:'soc', type:'job', parts:'pan',						name:'짜릿한 에너지 피해 증가'},
		{ver:'ori', job:'soc', type:'def', parts:'pan',						name:'불타오름 적에게 받는 피해 감소'},
		{ver:'ori', job:'soc', type:'skl', parts:'pan',						name:'구상번개'},
		{ver:'ori', job:'soc', type:'skl', parts:'pan',						name:'눈보라'},
		{ver:'ori', job:'soc', type:'skl', parts:'pan',						name:'운석낙하'},
		{ver:'ori', job:'soc', type:'skl', parts:'pan',						name:'화염벽'},
		{ver:'ori', job:'rog', type:'job', parts:'pan',						name:'공격 회피 후 4초 공격력'},
		{ver:'ori', job:'rog', type:'job', parts:'pan',						name:'주입 기술의 재사용 대기시간 감소'},
		{ver:'ori', job:'rog', type:'def', parts:'pan',						name:'중독 적에게 받는 피해 감소'},
		{ver:'ori', job:'rog', type:'skl', parts:'pan',						name:'맹독 덫'},
		{ver:'ori', job:'rog', type:'skl', parts:'pan',						name:'어둠의 장막'},
		{ver:'ori', job:'rog', type:'skl', parts:'pan',						name:'연막탄'},
		{ver:'ori', job:'rog', type:'skl', parts:'pan',						name:'은신'},
		{ver:'ori', job:'nec', type:'job', parts:'pan',						name:'최대 하수인 생명력'},
		{ver:'ori', job:'nec', type:'job', parts:'pan',						name:'피의 구슬 치유량'},
		{ver:'ori', job:'nec', type:'job', parts:'pan',						name:'골렘 가시 %'},
		{ver:'ori', job:'nec', type:'def', parts:'pan',						name:'보강상태에서 피해 감소'},
		{ver:'ori', job:'nec', type:'def', parts:'pan',						name:'지속 암흑 피해 효과의 영향을 받는 적에게 받는 피해 감소'},
		{ver:'ori', job:'nec', type:'skl', parts:'pan',						name:'뼈 감옥'},
		{ver:'ori', job:'nec', type:'skl', parts:'pan',						name:'시체 폭발'},
		{ver:'ori', job:'nec', type:'skl', parts:'pan',						name:'피 안개'},


		//장화
		{ver:'ori', job:'com', type:'com', parts:'boo',						name:'이동속도'},
		{ver:'ori', job:'com', type:'com', parts:'boo',						name:'정예 처치 후 4초 이동속도'},
		{ver:'ori', job:'com', type:'com', parts:'boo',						name:'감속 지속시간 감소'},
		{ver:'ori', job:'com', type:'com', parts:'boo',						name:'신단 효과 지속시간'},
		{ver:'ori', job:'com', type:'com', parts:'boo',						name:'부상 상태일 때 피해 감소'},
		{ver:'ori', job:'com', type:'com', parts:'boo',						name:'회피 확률'},
		{ver:'ori', job:'com', type:'com', parts:'boo',						name:'원거리에 있는 적에 대한 회피 확률'},
		{ver:'ori', job:'com', type:'com', parts:'boo',						name:'모든 능력치'},
		{ver:'ori', job:'com', type:'com', parts:'boo',						name:'힘'},
		{ver:'ori', job:'com', type:'com', parts:'boo',						name:'민첩'},
		{ver:'ori', job:'com', type:'com', parts:'boo',						name:'의지력'},
		{ver:'ori', job:'com', type:'com', parts:'boo',						name:'지능'},
		{ver:'ori', job:'com', type:'com', parts:'boo',						name:'화염 저항'},
		{ver:'ori', job:'com', type:'com', parts:'boo',						name:'냉기 저항'},
		{ver:'ori', job:'com', type:'com', parts:'boo',						name:'독 저항'},
		{ver:'ori', job:'com', type:'com', parts:'boo',						name:'번개 저항'},
		{ver:'ori', job:'com', type:'com', parts:'boo',						name:'암흑 저항'},
		{ver:'ori', job:'dru', type:'job', parts:'boo',						name:'영력 소모량 감소'},
		{ver:'ori', job:'dru', type:'job', parts:'boo',						name:'늑대인간 형상일 때 총 방어도'},
		{ver:'ori', job:'dru', type:'job', parts:'boo',						name:'보강 생성량'},
		{ver:'ori', job:'bab', type:'job', parts:'boo',						name:'분노 소모량 감소'},
		{ver:'ori', job:'bab', type:'job', parts:'boo',						name:'광폭화 지속 시간'},
		{ver:'ori', job:'bab', type:'job', parts:'boo',						name:'보강 생성량'},
		{ver:'ori', job:'soc', type:'job', parts:'boo',						name:'마나 소모량 감소'},
		{ver:'ori', job:'soc', type:'job', parts:'boo',						name:'짜릿한 에너지 피해 증가'},
		{ver:'ori', job:'soc', type:'skl', parts:'boo',						name:'화염 보호막'},
		{ver:'ori', job:'soc', type:'skl', parts:'boo',						name:'서릿발'},
		{ver:'ori', job:'soc', type:'skl', parts:'boo',						name:'얼음 갑옷'},
		{ver:'ori', job:'soc', type:'skl', parts:'boo',						name:'순간 이동'},
		{ver:'ori', job:'rog', type:'job', parts:'boo',						name:'기력 소모량 감소'},
		{ver:'ori', job:'rog', type:'skl', parts:'boo',						name:'쇠못 덫'},
		{ver:'ori', job:'rog', type:'skl', parts:'boo',						name:'질주'},
		{ver:'ori', job:'rog', type:'skl', parts:'boo',						name:'그림자 걸음'},
		{ver:'ori', job:'nec', type:'job', parts:'boo',						name:'정수 소모량 감소'},
		{ver:'ori', job:'nec', type:'job', parts:'boo',						name:'보강 생성량'},
		{ver:'ori', job:'nec', type:'job', parts:'boo',						name:'피의 구슬 치유량'},
		{ver:'ori', job:'nec', type:'skl', parts:'boo',						name:'뼈 영혼'},
		{ver:'ori', job:'nec', type:'skl', parts:'boo',						name:'시체 촉수'},

		//목걸이
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'가시'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'공격력'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'총 방어도'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'궁극기 기술 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'재사용 대기시간 감소'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'군중제어 효과의 지속시간'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'감속 지속시간 감소'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'제어 방해 지속시간 감소'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'부상당한 적에 대한 극대화 확률'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'피해 감소'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'근거리 적에게 받는 피해 감소'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'원거리 적에게 받는 피해 감소'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'부상상태일때 피해 감소'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'회피 확률'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'이동 속도'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'신단 강화 효과 지속시간'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'정예 처치 후 4초 공격력'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'정예 처치 후 4초 이동속도'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'힘 %'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'민첩 %'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'의지력 %'},
		{ver:'ori', job:'com', type:'com', parts:'amu',						name:'지능 %'},
		{ver:'ori', job:'dru', type:'job', parts:'amu',						name:'영력 소모량 감소'},
		{ver:'ori', job:'dru', type:'job', parts:'amu',						name:'폭풍 기술의 재사용 대기시간 감소'},
		{ver:'ori', job:'dru', type:'job', parts:'amu',						name:'곰인간 기술의 제압피해 증가'},
		{ver:'ori', job:'dru', type:'job', parts:'amu',						name:'늑대인간 형사일 때 총 방어도'},
		{ver:'ori', job:'dru', type:'job', parts:'amu',						name:'변신 상태에서 공격력'},
		{ver:'ori', job:'dru', type:'job', parts:'amu',						name:'인간 형상일 때 공격력'},
		{ver:'ori', job:'dru', type:'off', parts:'amu',						name:'곰인간 기술 피해 증가'},
		{ver:'ori', job:'dru', type:'off', parts:'amu',						name:'늑대인간 기술 피해 증가'},
		{ver:'ori', job:'dru', type:'off', parts:'amu',						name:'대지 기술 피해 증가'},
		{ver:'ori', job:'dru', type:'off', parts:'amu',						name:'동료 기술 피해 증가'},
		{ver:'ori', job:'dru', type:'off', parts:'amu',						name:'폭풍 기술 피해 증가'},
		{ver:'ori', job:'dru', type:'def', parts:'amu',						name:'보상 상태에서 피해 감소'},
		{ver:'ori', job:'dru', type:'skl', parts:'amu',						name:'모든 동료'},
		{ver:'ori', job:'dru', type:'skl', parts:'amu',						name:'모든 방어'},
		{ver:'ori', job:'dru', type:'skl', parts:'amu',						name:'모든 진노'},
		{ver:'ori', job:'dru', type:'skl', parts:'amu',						name:'공명'},
		{ver:'ori', job:'dru', type:'skl', parts:'amu',						name:'독살'},
		{ver:'ori', job:'dru', type:'skl', parts:'amu',						name:'독성 발톱'},
		{ver:'ori', job:'dru', type:'skl', parts:'amu',						name:'바위 경비병'},
		{ver:'ori', job:'dru', type:'skl', parts:'amu',						name:'반항'},
		{ver:'ori', job:'dru', type:'skl', parts:'amu',						name:'분열하는 대지'},
		{ver:'ori', job:'dru', type:'skl', parts:'amu',						name:'빠른 변신'},
		{ver:'ori', job:'dru', type:'skl', parts:'amu',						name:'야생의 부름'},
		{ver:'ori', job:'dru', type:'skl', parts:'amu',						name:'야생의 충동'},
		{ver:'ori', job:'dru', type:'skl', parts:'amu',						name:'자연의 테두리'},
		{ver:'ori', job:'dru', type:'skl', parts:'amu',						name:'자연 재해 지속효과'},
		{ver:'ori', job:'bab', type:'job', parts:'amu',						name:'분노 소모량 감소'},
		{ver:'ori', job:'bab', type:'job', parts:'amu',						name:'양손둔기의 제압 피해 증가'},
		{ver:'ori', job:'bab', type:'job', parts:'amu',						name:'쌍수 무기의 공격력'},
		{ver:'ori', job:'bab', type:'job', parts:'amu',						name:'양손 둔기의 공격력'},
		{ver:'ori', job:'bab', type:'job', parts:'amu',						name:'양손 베는 무기의 공격력'},
		{ver:'ori', job:'bab', type:'job', parts:'amu',						name:'광폭화 지속시간'},
		{ver:'ori', job:'bab', type:'off', parts:'amu',						name:'난기 기술 피해 증가'},
		{ver:'ori', job:'bab', type:'off', parts:'amu',						name:'무기 숙련 기술 피해 증가'},
		{ver:'ori', job:'bab', type:'off', parts:'amu',						name:'새로운 무기로 교체하는 기술 피해 증가'},
		{ver:'ori', job:'bab', type:'def', parts:'amu',						name:'보강 상태에서 피해 감소'},
		{ver:'ori', job:'bab', type:'skl', parts:'amu',						name:'모든 난투'},
		{ver:'ori', job:'bab', type:'skl', parts:'amu',						name:'무든 무기 숙련'},
		{ver:'ori', job:'bab', type:'skl', parts:'amu',						name:'모든 방어'},
		{ver:'ori', job:'bab', type:'skl', parts:'amu',						name:'맹공'},
		{ver:'ori', job:'bab', type:'skl', parts:'amu',						name:'무자비'},
		{ver:'ori', job:'bab', type:'skl', parts:'amu',						name:'묵직한 손'},
		{ver:'ori', job:'bab', type:'skl', parts:'amu',						name:'분노 폭발'},
		{ver:'ori', job:'bab', type:'skl', parts:'amu',						name:'뼈 가르기'},
		{ver:'ori', job:'bab', type:'skl', parts:'amu',						name:'야수의 힘'},
		{ver:'ori', job:'bab', type:'skl', parts:'amu',						name:'역공'},
		{ver:'ori', job:'bab', type:'skl', parts:'amu',						name:'철갑못'},
		{ver:'ori', job:'bab', type:'skl', parts:'amu',						name:'학살의 일격 지속효과'},
		{ver:'ori', job:'soc', type:'job', parts:'amu',						name:'마나 소모량 감소'},
		{ver:'ori', job:'soc', type:'job', parts:'amu',						name:'보호막이 있을 때 행운의 적중 확률'},
		{ver:'ori', job:'soc', type:'off', parts:'amu',						name:'감전 기술 피해 증가'},
		{ver:'ori', job:'soc', type:'off', parts:'amu',						name:'구현 기술 피해 증가'},
		{ver:'ori', job:'soc', type:'off', parts:'amu',						name:'방화 기술 피해 증가'},
		{ver:'ori', job:'soc', type:'off', parts:'amu',						name:'서리 기술 피해 증가'},
		{ver:'ori', job:'soc', type:'skl', parts:'amu',						name:'모든 구현'},
		{ver:'ori', job:'soc', type:'skl', parts:'amu',						name:'모든 방어'},
		{ver:'ori', job:'soc', type:'skl', parts:'amu',						name:'모든 숙련기술'},
		{ver:'ori', job:'soc', type:'skl', parts:'amu',						name:'감전의 충격'},
		{ver:'ori', job:'soc', type:'skl', parts:'amu',						name:'걸신들린 불길'},
		{ver:'ori', job:'soc', type:'skl', parts:'amu',						name:'구현 숙련'},
		{ver:'ori', job:'soc', type:'skl', parts:'amu',						name:'끝없는 장작'},
		{ver:'ori', job:'soc', type:'skl', parts:'amu',						name:'내면의 불꽃'},
		{ver:'ori', job:'soc', type:'skl', parts:'amu',						name:'얼음 손길'},
		{ver:'ori', job:'soc', type:'skl', parts:'amu',						name:'영구 결빙'},
		{ver:'ori', job:'soc', type:'skl', parts:'amu',						name:'원소 지배'},
		{ver:'ori', job:'soc', type:'skl', parts:'amu',						name:'유리 대포'},
		{ver:'ori', job:'soc', type:'skl', parts:'amu',						name:'흰 서리 지속 효과'},
		{ver:'ori', job:'rog', type:'job', parts:'amu',						name:'기력 소모량 감소'},
		{ver:'ori', job:'rog', type:'job', parts:'amu',						name:'덫 재사용 대기시간 감소'},
		{ver:'ori', job:'rog', type:'job', parts:'amu',						name:'주입 기술의 재사용 대기시간 감소'},
		{ver:'ori', job:'rog', type:'job', parts:'amu',						name:'덫의 충전 시간 감소'},
		{ver:'ori', job:'rog', type:'job', parts:'amu',						name:'공격 회피 후 4초 공격력'},
		{ver:'ori', job:'rog', type:'job', parts:'amu',						name:'쌍수 무기의 공격력'},
		{ver:'ori', job:'rog', type:'job', parts:'amu',						name:'원거리 무기의 공격력'},
		{ver:'ori', job:'rog', type:'off', parts:'amu',						name:'덫 기술 피해 증가'},
		{ver:'ori', job:'rog', type:'off', parts:'amu',						name:'명사수 기술 피해 증가'},
		{ver:'ori', job:'rog', type:'off', parts:'amu',						name:'암살 기술 피해 증가'},
		{ver:'ori', job:'rog', type:'off', parts:'amu',						name:'주입 기술 피해 증가'},
		{ver:'ori', job:'rog', type:'def', parts:'amu',						name:'중독 적에게 받는 피해 감소'},
		{ver:'ori', job:'rog', type:'skl', parts:'amu',						name:'모든 날쌘 몸놀림'},
		{ver:'ori', job:'rog', type:'skl', parts:'amu',						name:'모든 주입'},
		{ver:'ori', job:'rog', type:'skl', parts:'amu',						name:'모든 기만'},
		{ver:'ori', job:'rog', type:'skl', parts:'amu',						name:'무기 숙련'},
		{ver:'ori', job:'rog', type:'skl', parts:'amu',						name:'악의'},
		{ver:'ori', job:'rog', type:'skl', parts:'amu',						name:'자극'},
		{ver:'ori', job:'rog', type:'skl', parts:'amu',						name:'치명적인 맹독'},
		{ver:'ori', job:'rog', type:'skl', parts:'amu',						name:'착취'},
		{ver:'ori', job:'rog', type:'skl', parts:'amu',						name:'혹한의 기교 지속 효과'},
		{ver:'ori', job:'nec', type:'job', parts:'amu',						name:'정소 소모량 감소'},
		{ver:'ori', job:'nec', type:'job', parts:'amu',						name:'하수인 공격 속도'},
		{ver:'ori', job:'nec', type:'job', parts:'amu',						name:'지속 암흑 피해 증가'},
		{ver:'ori', job:'nec', type:'off', parts:'amu',						name:'뼈 기술 피해 증가'},
		{ver:'ori', job:'nec', type:'off', parts:'amu',						name:'소환 기술 피해 증가'},
		{ver:'ori', job:'nec', type:'off', parts:'amu',						name:'어둠 기술 피해 증가'},
		{ver:'ori', job:'nec', type:'off', parts:'amu',						name:'피 기술 피해 증가'},
		{ver:'ori', job:'nec', type:'def', parts:'amu',						name:'지속 암흑 피해 효과의 영향을 받는 적에게 받는 피해 감소'},
		{ver:'ori', job:'nec', type:'skl', parts:'amu',						name:'모든 섬뜩함'},
		{ver:'ori', job:'nec', type:'skl', parts:'amu',						name:'모든 시체'},
		{ver:'ori', job:'nec', type:'skl', parts:'amu',						name:'모든 저주'},
		{ver:'ori', job:'nec', type:'skl', parts:'amu',						name:'공포'},
		{ver:'ori', job:'nec', type:'skl', parts:'amu',						name:'복합 골절'},
		{ver:'ori', job:'nec', type:'skl', parts:'amu',						name:'불완전한 균형'},
		{ver:'ori', job:'nec', type:'skl', parts:'amu',						name:'어스름'},
		{ver:'ori', job:'nec', type:'skl', parts:'amu',						name:'응결된 피'},
		{ver:'ori', job:'nec', type:'skl', parts:'amu',						name:'적출'},
		{ver:'ori', job:'nec', type:'skl', parts:'amu',						name:'죽음의 손길'},
		{ver:'ori', job:'nec', type:'skl', parts:'amu',						name:'죽음의 동력'},
		{ver:'ori', job:'nec', type:'skl', parts:'amu',						name:'지옥의 사령관'},
		{ver:'ori', job:'nec', type:'skl', parts:'amu',						name:'피의 격류'},
		{ver:'ori', job:'nec', type:'skl', parts:'amu',						name:'피해 증폭 지속 효과'},

		//반지
		{ver:'ori', job:'com', type:'com', parts:'rin',						name:'극대화 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'rin',						name:'극대화 확률'},
		{ver:'ori', job:'com', type:'com', parts:'rin',						name:'취약 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'rin',						name:'자원 생성량'},
		{ver:'ori', job:'com', type:'com', parts:'rin',						name:'최근 피해를 받지 않았을 때 생명력 재생량'},
		{ver:'ori', job:'com', type:'com', parts:'rin',						name:'최대 생명력'},
		{ver:'ori', job:'com', type:'com', parts:'rin',						name:'행운의 적중 확률'},
		{ver:'ori', job:'com', type:'com', parts:'rin',						name:'감속 적에게 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'rin',						name:'군중제어 상태 효과의 영향을 받는 적에게 주는 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'rin',						name:'근거리 적에게 주는 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'rin',						name:'원거리 적에게 주는 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'rin',						name:'기적 적에게 주는 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'rin',						name:'부상당한 적에게 주는 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'rin',						name:'제압 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'rin',						name:'지속 피해 증가'},
		{ver:'ori', job:'dru', type:'job', parts:'rin',						name:'보강 생성량'},
		{ver:'ori', job:'dru', type:'job', parts:'rin',						name:'보호막 생성량'},
		{ver:'ori', job:'dru', type:'job', parts:'rin',						name:'최대 영력'},
		{ver:'ori', job:'dru', type:'job', parts:'rin',						name:'독 피해 증가'},
		{ver:'ori', job:'dru', type:'job', parts:'rin',						name:'물리 피해 증가'},
		{ver:'ori', job:'dru', type:'job', parts:'rin',						name:'번개 피해 증가'},
		{ver:'ori', job:'dru', type:'job', parts:'rin',						name:'중독된 적에게 주는 피해 증가'},
		{ver:'ori', job:'dru', type:'job', parts:'rin',						name:'늑대인간 기술의 극대화 피해 증가'},
		{ver:'ori', job:'dru', type:'job', parts:'rin',						name:'대지 기술의 극대화 피해 증가'},
		{ver:'ori', job:'dru', type:'job', parts:'rin',						name:'번개 극대화 피해 증가'},
		{ver:'ori', job:'bab', type:'job', parts:'rin',						name:'보강 생성량'},
		{ver:'ori', job:'bab', type:'job', parts:'rin',						name:'보호막 생성량'},
		{ver:'ori', job:'bab', type:'job', parts:'rin',						name:'최대 분노'},
		{ver:'ori', job:'bab', type:'job', parts:'rin',						name:'광폭화 상태일 때 공격력'},
		{ver:'ori', job:'bab', type:'job', parts:'rin',						name:'물리 피해 증가'},
		{ver:'ori', job:'bab', type:'job', parts:'rin',						name:'출혈 적에게 주는 피해 증가'},
		{ver:'ori', job:'soc', type:'job', parts:'rin',						name:'보호막 생성량'},
		{ver:'ori', job:'soc', type:'job', parts:'rin',						name:'최대 마나'},
		{ver:'ori', job:'soc', type:'job', parts:'rin',						name:'번개 극대화 피해 증가'},
		{ver:'ori', job:'soc', type:'job', parts:'rin',						name:'냉기 피해 증가'},
		{ver:'ori', job:'soc', type:'job', parts:'rin',						name:'번개 피해 증가'},
		{ver:'ori', job:'soc', type:'job', parts:'rin',						name:'화염 피해 증가'},
		{ver:'ori', job:'soc', type:'job', parts:'rin',						name:'짜릿한 에너지 피해 증가'},
		{ver:'ori', job:'soc', type:'job', parts:'rin',						name:'불타오름 적에게 주는 피해 증가'},
		{ver:'ori', job:'soc', type:'job', parts:'rin',						name:'빙결 적에게 주는 피해 증가'},
		{ver:'ori', job:'soc', type:'job', parts:'rin',						name:'오한 적에게 주는 피해 증가'},
		{ver:'ori', job:'rog', type:'job', parts:'rin',						name:'최대 기력'},
		{ver:'ori', job:'rog', type:'job', parts:'rin',						name:'주입 기술의 극대화 피해 증가'},
		{ver:'ori', job:'rog', type:'job', parts:'rin',						name:'냉기 피해 증가'},
		{ver:'ori', job:'rog', type:'job', parts:'rin',						name:'독 피해 증가'},
		{ver:'ori', job:'rog', type:'job', parts:'rin',						name:'물리 피해 증가'},
		{ver:'ori', job:'rog', type:'job', parts:'rin',						name:'암흑 피해 증가'},
		{ver:'ori', job:'rog', type:'job', parts:'rin',						name:'주입 기술의 피해 증가'},
		{ver:'ori', job:'rog', type:'job', parts:'rin',						name:'덫 기술의 영향을 받는 적에게 주는 피해 증가'},
		{ver:'ori', job:'rog', type:'job', parts:'rin',						name:'빙결 적에게 주는 피해 증가'},
		{ver:'ori', job:'rog', type:'job', parts:'rin',						name:'오한 적에게 주는 피해 증가'},
		{ver:'ori', job:'rog', type:'job', parts:'rin',						name:'중독 적에게 주는 피해 증가'},
		{ver:'ori', job:'nec', type:'job', parts:'rin',						name:'보강 생성량'},
		{ver:'ori', job:'nec', type:'job', parts:'rin',						name:'최대 정수'},
		{ver:'ori', job:'nec', type:'job', parts:'rin',						name:'최대 하수인 생명력'},
		{ver:'ori', job:'nec', type:'job', parts:'rin',						name:'피의 구슬 치유량'},
		{ver:'ori', job:'nec', type:'job', parts:'rin',						name:'피의 구슬을 주은 4초 공격력'},
		{ver:'ori', job:'nec', type:'job', parts:'rin',						name:'물리 피해 증가'},
		{ver:'ori', job:'nec', type:'job', parts:'rin',						name:'뼈 기술의 극대화 피해 증가'},
		{ver:'ori', job:'nec', type:'job', parts:'rin',						name:'암흑 피해 증가'},
		{ver:'ori', job:'nec', type:'job', parts:'rin',						name:'지속 암흑 피해 효과에 영향을 받는 적에게 주는 피해 증가'},
		{ver:'ori', job:'nec', type:'job', parts:'rin',						name:'골렘이 계승하는 가시'},
		{ver:'ori', job:'nec', type:'job', parts:'rin',						name:'해골 마법학자가 계승하는 가시'},
		{ver:'ori', job:'nec', type:'job', parts:'rin',						name:'해골 전사가 계승하는 가시'},

		//무기
		{ver:'ori', job:'com', type:'com', parts:'wep',						name:'극대화 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'wep',						name:'제압 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'wep',						name:'지속 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'wep',						name:'취약 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'wep',						name:'군중 제어 상태 효과의 영향을 받는 적에게 주는 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'wep',						name:'근거리 적에게 주는 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'wep',						name:'원거리 적에게 주는 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'wep',						name:'부상 당한 적에게 주는 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'wep',						name:'감속 적에게 주는 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'wep',						name:'기절 적에게 주는 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'wep',						name:'궁극기 기술 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'wep',						name:'기본 기술 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'wep',						name:'핵심 기술 피해 증가'},
		{ver:'ori', job:'com', type:'com', parts:'wep',						name:'행운의 적중: 부상당한 비저예 적 처형 확률'},
		{ver:'ori', job:'dru', type:'job', parts:'wep',						name:'의지력'},
		{ver:'ori', job:'dru', type:'job', parts:'wep',						name:'곰인간 기술의 제압 피해 증가'},
		{ver:'ori', job:'dru', type:'job', parts:'wep',						name:'늑대인간 기술의 극대화 피해 증가'},
		{ver:'ori', job:'dru', type:'job', parts:'wep',						name:'대지 기술의 극대화 피해 증가'},
		{ver:'ori', job:'dru', type:'job', parts:'wep',						name:'번개 기술의 극대화 피해 증가'},
		{ver:'ori', job:'dru', type:'job', parts:'wep',						name:'중독 적에게 주는 피해 증가'},
		{ver:'ori', job:'bab', type:'job', parts:'wep',						name:'힘'},
		{ver:'ori', job:'bab', type:'job', parts:'wep',						name:'광폭화 상태일 때 공격력'},
		{ver:'ori', job:'bab', type:'job', parts:'wep',						name:'출혈 적에게 주는 피해 증가'},
		{ver:'ori', job:'soc', type:'job', parts:'wep',						name:'지능'},
		{ver:'ori', job:'soc', type:'job', parts:'wep',						name:'번개 극대화 피해 증가'},
		{ver:'ori', job:'soc', type:'job', parts:'wep',						name:'불타오름 적에게 주는 피해 증가'},
		{ver:'ori', job:'soc', type:'job', parts:'wep',						name:'빙결 적에게 주는 피해 증가'},
		{ver:'ori', job:'soc', type:'job', parts:'wep',						name:'오한 적어게 주는 피해 증가'},
		{ver:'ori', job:'rog', type:'job', parts:'wep',						name:'민첩'},
		{ver:'ori', job:'rog', type:'job', parts:'wep',						name:'주입 기술의 극대화 피해 증가'},
		{ver:'ori', job:'rog', type:'job', parts:'wep',						name:'덫 기술의 영향을 받는 적에게 주는 피해 증가'},
		{ver:'ori', job:'rog', type:'job', parts:'wep',						name:'멍해짐 적에게 주는 피해 증가'},
		{ver:'ori', job:'rog', type:'job', parts:'wep',						name:'빙결 적에게 주는 피해 증가'},
		{ver:'ori', job:'rog', type:'job', parts:'wep',						name:'오한 적에게 주는 피해 증가'},
		{ver:'ori', job:'rog', type:'job', parts:'wep',						name:'중독 적에게 주는 피해 증가'},
		{ver:'ori', job:'nec', type:'job', parts:'wep',						name:'지능'},
		{ver:'ori', job:'nec', type:'job', parts:'wep',						name:'지속 암흑 피해 효과의 영향을 받는 적에게 주는 피해 증가'},
		{ver:'ori', job:'nec', type:'job', parts:'wep',						name:'뼈 기술의 극대화 피해 증가'},

		//보조무기
		{ver:'ori', job:'nec', type:'off', parts:'wep',						name:'피해 증가'},

		//방패
		{ver:'ori', job:'nec', type:'off', parts:'wep',						name:'피해 증가'},
	];
	method.init = function(){
		obj.wrap = $('#optionList')
		$.each(options, function(index, option){
			obj.wrap.append('<span id="itemOption'+index+'" class="grid-option '+option.parts+'" data-option-job="'+option.job+'" data-option-type="'+option.type+'"><input type="checkbox" class="option-fav"><button type="button" class="option-name">'+option.name+'</button><button type="button" class="option-del">삭제</button></span>');
		});
		obj.wrap.find('[data-option-type=com]').wrapAll('<span class="option-group" data-group="com"></span>');
		//obj.wrap.find('[data-option-type=off]').wrapAll('<span class="option-group" data-group="off"></span>');
		//obj.wrap.find('[data-option-type=job]').wrapAll('<span class="option-group" data-group="job"></span>');
		obj.wrap.find('[data-option-type=job], [data-option-type=off]').wrapAll('<span class="option-group" data-group="job"></span>');
		obj.wrap.find('[data-option-type=def]').wrapAll('<span class="option-group" data-group="def"></span>');
		obj.wrap.find('[data-option-type=skl]').wrapAll('<span class="option-group" data-group="skl"></span>');
		obj.wrap.find('[data-option-type=etc]').wrapAll('<span class="option-group" data-group="etc"></span>');
	};
	return{
		init : method.init
	}
})();
D4Option.init();